spring:
  config:
    import: optional:classpath:application-local.yaml

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/flowe_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:}

  sql:
    init:
      mode: always

server:
  port: 8080